# Generated by Django 2.1.4 on 2018-12-21 06:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pingtai', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('con', ckeditor.fields.RichTextField(max_length=20000, verbose_name='文章内容')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Category', verbose_name='分类')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Keyword', verbose_name='关键字')),
            ],
        ),
    ]
