# Generated by Django 2.1.4 on 2018-12-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('pingtai', '0003_ptarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='公司')),
                ('position', models.CharField(max_length=30, verbose_name='职位')),
                ('hobby', models.CharField(max_length=100, verbose_name='爱好')),
                ('reason', models.TextField(max_length=300, verbose_name='原因')),
                ('realname', models.CharField(max_length=20, verbose_name='姓名')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('p_time', models.DateTimeField(auto_now=True, verbose_name='通过时间')),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.User')),
            ],
        ),
    ]
