# Generated by Django 2.1.4 on 2018-12-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0004_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类管理'},
        ),
        migrations.AlterModelOptions(
            name='ptarticle',
            options={'verbose_name': '添加文章'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '博客审核', 'verbose_name_plural': '博客审核'},
        ),
        migrations.AddField(
            model_name='ptarticle',
            name='look',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
