# Generated by Django 2.1.4 on 2018-12-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='a',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='c',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='k',
        ),
        migrations.DeleteModel(
            name='Artical',
        ),
    ]
