# Generated by Django 2.1.4 on 2018-12-26 05:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0002_auto_20181226_1123'),
        ('pingtai', '0005_auto_20181226_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('con', ckeditor.fields.RichTextField(max_length=20000, verbose_name='文章内容')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('look', models.IntegerField(default=0, verbose_name='浏览量')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.User')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Category', verbose_name='分类')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Keyword', verbose_name='关键字')),
            ],
        ),
    ]
