# Generated by Django 2.1.4 on 2018-12-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='status',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
    ]
